### ISSUE TITLE
x_x 之 电影名净化器：修改建议~~ (>o<)~~

### ISSUE THREAD

**Issue by elliotxx** [WangHaizhen/py-tree#10]
代码改进建议：
* path = 'd:\\xxx' 可以写成 path = r'd:\xxx'
* 函数 GetFileList(dir, fileList) 的参数 fileList 可以定义在 函数内部
* replace("[","l") 为什么不改成 replace("[","") 呢？
* .split('.') 是想让宝宝在函数 clear 中的一开始用的，把文件名和后缀名分离开
* 可以把 import base64 去掉啦

还有几个问题：
* 如果文件名中 【】、[] 不配对怎么办呢？
* 如果目录里有其它文件名字里带有【】，[] 等符号，也要一并处理吗？

加油宝宝！~~ 代码有进步~~~

**Comment by WangHaizhen** [comment]
回复里边如果有表情就好了，你经历过绝望吗

**Comment by elliotxx** [comment]
还有有几个表情的

**Comment by WangHaizhen** [comment]
已实现
自己需要注意的问题：
编码问题例如：fp = fp.replace(u"【","l").replace(u"】","l")
