### ISSUE TITLE
w_1_1 模块还可以再封装一下~ 

### ISSUE THREAD

**Issue by elliotxx** [WangHaizhen/py-tree#4]
w_1_1.py 部分代码
```
if __name__=='__main__':
	while True:
		s = input('Please enter string:')
		if IP(s):
			print('.'.join(s.split()))
		else:
			print('[Error]: cannot compose IP address')
```
这里的部分代码可以再封装成一个函数，**提示**：
**函数的传入**：一个用空格分隔的 IP 字符串
**函数的返回值**：用 . 分隔的 IP 字符串
**函数的功能**：检查传入的 IP 字符串是否合法，不合法输出提示信息，合法返回拼接之后的 IP 字符串

**封装原因**：w_1_1 和 w_1_2 这两个文件有一段类似的代码，完全可以在 1_1 中封装好之后在 1_2 中直接调用

**Comment by elliotxx** [comment]
加油 ~~ ↖(^ω^)↗

**Comment by WangHaizhen** [comment]
么么哒
