### ISSUE TITLE
【总结】送宝宝一朵小红花~

### ISSUE THREAD

**Issue by elliotxx** [WangHaizhen/py-tree#8]
ヾ(❀撒花╹◡╹)ﾉ~ ✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ
✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿。
✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿。
✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿。
✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿。
✿.｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿ ｡.･:*✿*ﾟ¨ﾟ✎･✿.｡.✿*ﾟ¨ﾟ✎･✿。

```加油~     \*★,°*:.☆\(￣▽￣)/$:*.°★\* 。 ```

**Comment by WangHaizhen** [comment]
么么哒
