### ISSUE TITLE
w_2_4 找游戏的一个小 bug ~

### ISSUE THREAD

**Issue by elliotxx** [WangHaizhen/py-tree#9]
这个 bug 是这样的：**如果输入 >8 的 competition ，程序就会报错**。

这里我不提示，宝宝可以自己尝试去 fix the bug ~

Fix 之后可以把错误原因回复在下面，记录下来 ↓

这题写得不错呦！~

**Comment by WangHaizhen** [comment]
debug产生原因：range(0,10),只能产生9个随机整数，所以只要当士兵个数超过9时，就会报错
debug解决方法：在电脑派出敌人时，用while循环来产生对抗者，这样就可以解决人数限制的问题

**Comment by elliotxx** [comment]
棒棒哒~ 小宝宝

**Comment by elliotxx** [comment]
程序基本没有什么逻辑问题了，现在可以尝试把代码精简一下。
比如生成随机数那里可以用列表解析代替，if ... else ... 语句可以写成一行。
总之尝试把代码写得更优美吧！ :+1:

**Comment by WangHaizhen** [comment]
已优化
